name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  assumeutxo-signet:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 120
    env:
      NIX_PATH: nixpkgs=channel:nixos-unstable
      # utxo.dat should be outside any $HOME dir due to NixOS service security settings
      UTXO_PATH: /var/lib/bitcoin/utxo-signet-160000.dat
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: $NIX_PATH
      - name: Run AssumeUTXO
        env:
          TMP_DATADIR: "${{ runner.temp }}/base_datadir"
        run: |
          env
          mkdir -p "$TMP_DATADIR"
          nix-shell --command "just run-assumeutxo-signet-ci $TMP_DATADIR $UTXO_PATH ${{ github.event.pull_request.base.sha }} ${{github.event.pull_request.head.sha}} ${{ runner.temp }}/results.json"
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: "${{ runner.temp }}/results.json"
      - uses: actions/upload-artifact@v4
        with:
          name: flamegraph
          path: "$TMP_DATADIR/flamegraph.html"
      - name: Write GitHub and runner context files
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          mkdir contexts
          echo "$GITHUB_CONTEXT" | nix-shell -p jq --command "jq 'del(.token)' > contexts/github.json"
          echo "$RUNNER_CONTEXT" > contexts/runner.json
      - name: Upload context metadata as artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-metadata
          path: ./contexts/
